### PR TITLE
Create Arabic.ini

### PR DESCRIPTION
**Pull request by salehif**
Arabic language

### CODE REVIEW

**Comment by iowbeoibewio** [comment]
the file not complete yet

**Comment by murrty** [comment]
Thanks for doing translations, let me know when you're finished and I'll merge it into the master

**Comment by salehif** [comment]
- file complete 100% translation from English to Arabic.
- optimize texts to be able reading from right to left.
- clear and add some sentences, so some options be more clear to users (some words can't be understandable if translated to Arabic literally).
- all translation based on using and how app works, so user can understand what every option means and do.

and thanks to murrty for making GUI for youtube-dl

**Comment by salehif** [comment]
Capture
Capture1
Capture2

**Comment by murrty** [comment]
Thanks for translating, I was going to consider right-to-left but I don't know the proper etiquette for it, so I'm just gonna skip on it for now.

**Pull request merged**
